---
- name: Uninstall Java
  apt:
    name: "{{ java_version }}"
    state: absent

- name: Check if Java is still installed
  command: java -version
  register: java_version_output
  ignore_errors: true
  changed_when: false

- name: Show remaining Java version, if any
  debug:
    var: java_version_output.stdout_lines
  when: java_version_output.rc == 0

- name: Confirm Java version is uninstalled
  debug:
    msg: "The specified Java version has been successfully uninstalled!"
  when: java_version_output.rc != 0