---
- name: Uninstall Java
  apt:
    name: "{{ java_version }}"
    state: absent

# - name: Remove any remaining Java-related directories
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - "/usr/lib/jvm"
#     - "/etc/java-*"
#     - "/usr/lib/jvm-*"

- name: Reload systemd configuration
  command: systemctl daemon-reload

- name: Check if Java is still installed
  command: java -version
  register: java_version_output
  ignore_errors: true
  changed_when: false

- name: Show remaining Java version, if any
  debug:
    var: java_version_output.stderr
  when: java_version_output.rc == 0

- name: Confirm Java is uninstalled
  debug:
    msg: "Java has been completely purged from the system!"
  when: java_version_output.rc != 0